use crate::config::Language;

/// All UI text strings used in the settings window and overlay.
/// Add new fields here when adding new settings; never hard-code text in GUI files.
#[allow(dead_code)]
pub struct Strings {
    // ── Sidebar tabs ─────────────────────────────────────────────────────────
    pub tab_aimbot: &'static str,
    pub tab_player: &'static str,
    pub tab_hud: &'static str,
    pub tab_grenades: &'static str,
    pub tab_unsafe: &'static str,
    pub tab_config: &'static str,
    pub tab_application: &'static str,

    // ── Sidebar status / buttons ──────────────────────────────────────────────
    pub status_connected: &'static str,
    pub status_waiting: &'static str,
    pub btn_report_issue: &'static str,
    pub btn_about: &'static str,
    pub search_placeholder: &'static str,

    // ── Common ────────────────────────────────────────────────────────────────
    pub enable: &'static str,
    pub hotkey: &'static str,
    pub mode: &'static str,
    pub mode_hold: &'static str,
    pub mode_toggle: &'static str,
    pub mode_always: &'static str,
    pub enable_override: &'static str,
    pub global: &'static str,
    pub weapon: &'static str,

    // ── Aimbot ────────────────────────────────────────────────────────────────
    pub section_aimbot: &'static str,
    pub section_targeting: &'static str,
    pub section_checks: &'static str,
    pub section_bones: &'static str,

    pub aimbot_fov: &'static str,
    pub aimbot_smooth: &'static str,
    pub aimbot_start_bullet: &'static str,
    pub aimbot_targeting_mode: &'static str,
    pub aimbot_target_friendlies: &'static str,
    pub aimbot_distance_fov: &'static str,
    pub aimbot_visibility_check: &'static str,
    pub aimbot_flash_check: &'static str,

    // tooltips
    pub tip_aimbot_enable: &'static str,
    pub tip_aimbot_mode_hold: &'static str,
    pub tip_aimbot_mode_toggle: &'static str,
    pub tip_aimbot_mode_always: &'static str,
    pub tip_enable_override: &'static str,
    pub tip_aimbot_fov: &'static str,
    pub tip_aimbot_smooth: &'static str,
    pub tip_aimbot_start_bullet: &'static str,
    pub tip_aimbot_distance_fov: &'static str,
    pub tip_aimbot_visibility: &'static str,
    pub tip_aimbot_flash: &'static str,
    pub tip_aimbot_target_friendlies: &'static str,

    // ── Triggerbot ────────────────────────────────────────────────────────────
    pub section_triggerbot: &'static str,
    pub triggerbot_delay: &'static str,
    pub triggerbot_shot_duration: &'static str,
    pub triggerbot_flash_check: &'static str,
    pub triggerbot_scope_check: &'static str,
    pub triggerbot_velocity_check: &'static str,
    pub triggerbot_velocity_threshold: &'static str,
    pub triggerbot_head_only: &'static str,
    pub triggerbot_wallbang: &'static str,

    pub tip_triggerbot_enable: &'static str,
    pub tip_triggerbot_delay: &'static str,
    pub tip_triggerbot_shot_duration: &'static str,
    pub tip_triggerbot_flash: &'static str,
    pub tip_triggerbot_scope: &'static str,
    pub tip_triggerbot_velocity: &'static str,
    pub tip_triggerbot_head_only: &'static str,
    pub tip_triggerbot_wallbang: &'static str,

    // ── RCS ───────────────────────────────────────────────────────────────────
    pub section_rcs: &'static str,
    pub rcs_strength: &'static str,
    pub rcs_mode: &'static str,
    pub rcs_smoothing: &'static str,

    pub tip_rcs_enable: &'static str,
    pub tip_rcs_strength: &'static str,
    pub tip_rcs_mode: &'static str,
    pub tip_rcs_smoothing: &'static str,

    // ── Player / ESP ──────────────────────────────────────────────────────
    pub section_players: &'static str,
    pub section_sound_esp: &'static str,
    pub section_colors: &'static str,

    pub player_esp_hotkey: &'static str,
    pub player_show_friendlies: &'static str,
    pub player_bomb_damage: &'static str,
    pub player_box: &'static str,
    pub player_box_mode: &'static str,
    pub player_skeleton: &'static str,
    pub player_head_circle: &'static str,
    pub player_health_bar: &'static str,
    pub player_armor_bar: &'static str,
    pub player_name: &'static str,
    pub player_weapon_icon: &'static str,
    pub player_tags: &'static str,
    pub player_visible_only: &'static str,

    pub sound_footstep_radius: &'static str,
    pub sound_gunshot_radius: &'static str,
    pub sound_weapon_radius: &'static str,
    pub sound_fade_start: &'static str,
    pub sound_fade_duration: &'static str,
    pub sound_show_visible: &'static str,

    pub color_box_visible: &'static str,
    pub color_box_invisible: &'static str,
    pub color_skeleton: &'static str,
    pub color_player_name: &'static str,
    pub color_weapon_icon: &'static str,
    pub color_tags: &'static str,

    pub tip_player_enable: &'static str,
    pub tip_player_visible_only: &'static str,
    pub tip_player_show_friendlies: &'static str,
    pub tip_player_health_bar: &'static str,
    pub tip_player_armor_bar: &'static str,
    pub tip_player_tags: &'static str,
    pub tip_sound_esp: &'static str,
    pub tip_bomb_damage: &'static str,

    // ── HUD ───────────────────────────────────────────────────────────────────
    pub section_hud: &'static str,
    pub section_text: &'static str,
    pub section_crosshair: &'static str,
    pub section_grenade_trails: &'static str,
    pub section_radar: &'static str,

    pub hud_bomb_timer: &'static str,
    pub hud_fov_circle: &'static str,
    pub hud_dropped_weapons: &'static str,
    pub hud_keybind_list: &'static str,
    pub hud_spectator_list: &'static str,
    pub hud_text_outline: &'static str,
    pub hud_text_color: &'static str,
    pub hud_line_width: &'static str,
    pub hud_font_size: &'static str,
    pub hud_icon_size: &'static str,

    pub crosshair_enable: &'static str,
    pub crosshair_color: &'static str,
    pub crosshair_line_length: &'static str,
    pub crosshair_line_width: &'static str,
    pub crosshair_gap: &'static str,

    pub radar_enable: &'static str,
    pub radar_size: &'static str,
    pub radar_zoom: &'static str,
    pub radar_rotate: &'static str,
    pub radar_show_names: &'static str,
    pub radar_bg_alpha: &'static str,

    pub tip_hud_bomb_timer: &'static str,
    pub tip_hud_fov_circle: &'static str,
    pub tip_hud_spectator_list: &'static str,
    pub tip_crosshair_enable: &'static str,
    pub tip_radar_enable: &'static str,
    pub tip_radar_rotate: &'static str,

    // ── Unsafe ────────────────────────────────────────────────────────────────
    pub section_no_flash: &'static str,
    pub section_fov_changer: &'static str,
    pub section_smokes: &'static str,

    pub unsafe_no_flash: &'static str,
    pub unsafe_max_flash: &'static str,
    pub unsafe_fov_changer: &'static str,
    pub unsafe_desired_fov: &'static str,
    pub unsafe_no_smoke: &'static str,
    pub unsafe_change_smoke_color: &'static str,
    pub unsafe_smoke_color: &'static str,

    pub tip_no_flash: &'static str,
    pub tip_unsafe_max_flash: &'static str,
    pub tip_fov_changer: &'static str,
    pub tip_no_smoke: &'static str,
    pub tip_change_smoke_color: &'static str,

    // ── Config ────────────────────────────────────────────────────────────────
    pub section_config: &'static str,
    pub config_reset: &'static str,
    pub config_folder: &'static str,
    pub config_refresh: &'static str,
    pub config_new_name: &'static str,
    pub config_save_as: &'static str,
    pub config_delete: &'static str,
    pub config_load: &'static str,

    pub tip_config_reset: &'static str,

    // ── Application ───────────────────────────────────────────────────────────
    pub section_application: &'static str,
    pub app_language: &'static str,
    pub app_send_stacktraces: &'static str,
    pub app_stacktraces_yes: &'static str,
    pub app_stacktraces_no: &'static str,

    pub tip_app_language: &'static str,
    pub tip_send_stacktraces: &'static str,
}

// ─────────────────────────────────────────────────────────────────────────────
// English
// ─────────────────────────────────────────────────────────────────────────────
pub const LANG_EN: Strings = Strings {
    tab_aimbot: "\u{f04fe}  Aimbot",
    tab_player: "\u{f0013}  Visuals",
    tab_hud: "\u{f0379}  HUD",
    tab_grenades: "\u{f0691}  Grenades",
    tab_unsafe: "\u{f0ce6}  Unsafe",
    tab_config: "\u{f168b}  Config",
    tab_application: "\u{f1577}  Application",

    status_connected: "● Connected",
    status_waiting: "● Waiting…",
    btn_report_issue: "Report Issue",
    btn_about: "About",
    search_placeholder: "Search settings…",

    enable: "Enable",
    hotkey: "Hotkey",
    mode: "Mode",
    mode_hold: "Hold",
    mode_toggle: "Toggle",
    mode_always: "Always",
    enable_override: "Enable Override",
    global: "Global",
    weapon: "Weapon",

    section_aimbot: "Aimbot",
    section_targeting: "Targeting",
    section_checks: "Checks",
    section_bones: "Bones",

    aimbot_fov: "FOV",
    aimbot_smooth: "Smooth",
    aimbot_start_bullet: "Start Bullet",
    aimbot_targeting_mode: "Targeting Mode",
    aimbot_target_friendlies: "Target Friendlies",
    aimbot_distance_fov: "Distance-Adjusted FOV",
    aimbot_visibility_check: "Visibility Check",
    aimbot_flash_check: "Flash Check",

    tip_aimbot_enable: "Enables automatic aiming at the nearest visible enemy.",
    tip_aimbot_mode_hold: "Aimbot is active only while the hotkey is held.",
    tip_aimbot_mode_toggle: "Press the hotkey to toggle aimbot on/off.",
    tip_aimbot_mode_always: "Aimbot is always active without any hotkey.",
    tip_enable_override: "Override the global aimbot settings for this specific weapon.",
    tip_aimbot_fov: "Maximum angle (°) from crosshair in which the aimbot locks onto a target.",
    tip_aimbot_smooth: "Higher = smoother/slower aiming movement. 0 = instant snap.",
    tip_aimbot_start_bullet: "Aimbot activates only after this many shots have been fired.",
    tip_aimbot_distance_fov: "Automatically widens FOV for distant targets so you still lock on.",
    tip_aimbot_visibility: "Only aim at enemies that are truly visible (not behind walls).",
    tip_aimbot_flash: "Stop aiming when the local player is flashed.",
    tip_aimbot_target_friendlies: "Also aim at teammates (useful in FFA modes).",

    section_triggerbot: "Triggerbot",
    triggerbot_delay: "Delay (ms)",
    triggerbot_shot_duration: "Shot Duration (ms)",
    triggerbot_flash_check: "Flash Check",
    triggerbot_scope_check: "Scope Check",
    triggerbot_velocity_check: "Velocity Check",
    triggerbot_velocity_threshold: "Velocity Threshold",
    triggerbot_head_only: "Head Only",
    triggerbot_wallbang: "Wallbang",

    tip_triggerbot_enable: "Automatically fires when the crosshair is over an enemy.",
    tip_triggerbot_delay: "Random delay range (min–max ms) before firing, to look more human.",
    tip_triggerbot_shot_duration: "How long the virtual click is held down (ms).",
    tip_triggerbot_flash: "Do not fire while flashed.",
    tip_triggerbot_scope: "For snipers: only fire while scoped in.",
    tip_triggerbot_velocity: "Do not fire while moving faster than this threshold.",
    tip_triggerbot_head_only: "Only fire when the crosshair is directly over the enemy's head.",
    tip_triggerbot_wallbang: "Fire through walls when an enemy is along the aim line. Enable per-weapon for guns with penetration.",

    section_rcs: "Recoil Control (RCS)",
    rcs_strength: "Strength",
    rcs_mode: "Mode",
    rcs_smoothing: "Smoothing",
    tip_rcs_enable: "Compensates for weapon recoil by moving the mouse opposite the punch.",
    tip_rcs_strength: "Compensation strength per axis (0 = off, 1 = full).",
    tip_rcs_mode: "Standalone: always active while shooting. Aiming: only active when aimbot has a locked target.",
    tip_rcs_smoothing: "Smooths the correction over multiple frames (0 = instant, 0.9 = heavy). Makes recoil control look more natural.",

    section_players: "Players",
    section_sound_esp: "Sound ESP",
    section_colors: "Colors",

    player_esp_hotkey: "ESP Hotkey",
    player_show_friendlies: "Show Friendlies",
    player_bomb_damage: "Bomb Damage",
    player_box: "Box",
    player_box_mode: "Box Mode",
    player_skeleton: "Skeleton",
    player_head_circle: "Head Circle",
    player_health_bar: "Health Bar",
    player_armor_bar: "Armor Bar",
    player_name: "Player Name",
    player_weapon_icon: "Weapon Icon",
    player_tags: "Tags",
    player_visible_only: "Visible Only",

    sound_footstep_radius: "Footstep Radius",
    sound_gunshot_radius: "Gunshot Radius",
    sound_weapon_radius: "Weapon Radius",
    sound_fade_start: "Fade Start (s)",
    sound_fade_duration: "Fade Duration (s)",
    sound_show_visible: "Show for Visible Players",

    color_box_visible: "Box (visible)",
    color_box_invisible: "Box (invisible)",
    color_skeleton: "Skeleton",
    color_player_name: "Player Name",
    color_weapon_icon: "Weapon Icon",
    color_tags: "Tags (Bomb / Helmet)",

    tip_player_enable: "Draw ESP boxes, skeletons and labels over enemies.",
    tip_player_visible_only: "Only draw players that have a clear line of sight to you.",
    tip_player_show_friendlies: "Also draw ESP for teammates.",
    tip_player_health_bar: "Show a health bar on the left side of the ESP box.",
    tip_player_armor_bar: "Show an armor bar on the right side of the ESP box.",
    tip_player_tags: "Show bomb carrier / defuser icon above the box.",
    tip_sound_esp: "Show circles representing recently heard footstep / gunshot sounds.",
    tip_bomb_damage: "Show estimated remaining HP after C4 detonation next to each player's box.",

    section_hud: "HUD",
    section_text: "Text",
    section_crosshair: "Sniper Crosshair",
    section_grenade_trails: "Grenade Trails",
    section_radar: "Radar",

    hud_bomb_timer: "Bomb Timer",
    hud_fov_circle: "FOV Circle",
    hud_dropped_weapons: "Dropped Weapons",
    hud_keybind_list: "Keybind List",
    hud_spectator_list: "Spectator List",
    hud_text_outline: "Text Outline",
    hud_text_color: "Text Color",
    hud_line_width: "Line Width",
    hud_font_size: "Font Size",
    hud_icon_size: "Icon Size",

    crosshair_enable: "Enable Crosshair",
    crosshair_color: "Crosshair Color",
    crosshair_line_length: "Line Length",
    crosshair_line_width: "Line Width",
    crosshair_gap: "Gap",

    radar_enable: "In-Game Radar Hack",
    radar_size: "Size (px)",
    radar_zoom: "Zoom",
    radar_rotate: "Rotate with Player",
    radar_show_names: "Show Names",
    radar_bg_alpha: "Background Alpha",

    tip_hud_bomb_timer: "Display a countdown bar and 3D text when the bomb is planted.",
    tip_hud_fov_circle: "Draw a circle on the overlay showing the aimbot's lock-on radius.",
    tip_hud_spectator_list: "Show a list of players who are currently spectating you.",
    tip_crosshair_enable: "Draw a custom crosshair when using a scoped weapon.",
    tip_radar_enable: "Writes the spotted flag for all enemies so they appear on the CS2 minimap.",
    tip_radar_rotate: "Rotate the radar so the player always faces up.",

    section_no_flash: "No Flash",
    section_fov_changer: "FOV Changer",
    section_smokes: "Smokes",

    unsafe_no_flash: "No Flash",
    unsafe_max_flash: "Max Flash Alpha",
    unsafe_fov_changer: "FOV Changer",
    unsafe_desired_fov: "Desired FOV",
    unsafe_no_smoke: "No Smoke",
    unsafe_change_smoke_color: "Change Smoke Color",
    unsafe_smoke_color: "Smoke Color",

    tip_no_flash: "Reduce or eliminate the blinding flash effect.",
    tip_unsafe_max_flash: "0 = fully blocked (no flash), 255 = normal flash. Lower values reduce the blinding effect more.",
    tip_fov_changer: "Override your in-game field of view.",
    tip_no_smoke: "Remove smoke grenade particle effects.",
    tip_change_smoke_color: "Replace smoke with a custom solid color.",

    section_config: "Config",
    config_reset: "Legit Default",
    config_folder: "Open Config Folder",
    config_refresh: "Refresh",
    config_new_name: "New config name…",
    config_save_as: "Save",
    config_delete: "Delete",
    config_load: "Load",
    tip_config_reset: "Resets all settings to VAC-safe legit defaults (aimbot/triggerbot/rcs/unsafe all off, ESP stays on).",

    section_application: "Application",
    app_language: "Language",
    app_send_stacktraces: "Send crash reports",
    app_stacktraces_yes: "Yes – help improve the tool",
    app_stacktraces_no: "No",
    tip_app_language: "Select the UI display language.",
    tip_send_stacktraces: "Automatically send crash stack traces to help fix bugs.",
};

// ─────────────────────────────────────────────────────────────────────────────
// Turkish
// ─────────────────────────────────────────────────────────────────────────────
pub const LANG_TR: Strings = Strings {
    tab_aimbot: "\u{f04fe}  Nişan",
    tab_player: "\u{f0013}  Görseller",
    tab_hud: "\u{f0379}  HUD",
    tab_grenades: "\u{f0691}  Grenadlar",
    tab_unsafe: "\u{f0ce6}  Güvensiz",
    tab_config: "\u{f168b}  Yapılandırma",
    tab_application: "\u{f1577}  Uygulama",

    status_connected: "● Bağlandı",
    status_waiting: "● Bekleniyor…",
    btn_report_issue: "Hata Bildir",
    btn_about: "Hakkında",
    search_placeholder: "Ayarlarda ara…",

    enable: "Etkinleştir",
    hotkey: "Kısayol Tuş",
    mode: "Mod",
    mode_hold: "Basılı Tut",
    mode_toggle: "Aç/Kapat",
    mode_always: "Her Zaman",
    enable_override: "Silah Geçersiz Kılma",
    global: "Global",
    weapon: "Silah",

    section_aimbot: "Aimbot",
    section_targeting: "Hedefleme",
    section_checks: "Kontroller",
    section_bones: "Kemikler",

    aimbot_fov: "FOV",
    aimbot_smooth: "Yumuşatma",
    aimbot_start_bullet: "Başlangıç Mermisi",
    aimbot_targeting_mode: "Hedefleme Modu",
    aimbot_target_friendlies: "Takım Arkadaşlarını Hedefle",
    aimbot_distance_fov: "Mesafeye Göre FOV",
    aimbot_visibility_check: "Görünürlük Kontrolü",
    aimbot_flash_check: "Flaş Kontrolü",

    tip_aimbot_enable: "En yakın görünen düşmana otomatik nişan alır.",
    tip_aimbot_mode_hold: "Kısayol tuşuna basıldığı sürece aimbot aktif kalır.",
    tip_aimbot_mode_toggle: "Kısayol tuşuna basarak aimbot'u aç/kapat.",
    tip_aimbot_mode_always: "Aimbot herhangi bir tuşa gerek duymadan sürekli aktiftir.",
    tip_enable_override: "Bu silah için global aimbot ayarlarını geçersiz kıl.",
    tip_aimbot_fov: "Crosshair'den en fazla bu kadar derece uzaktaki hedeflere kilitlenir.",
    tip_aimbot_smooth: "Yüksek değer = daha yumuşak/yavaş nişan hareketi. 0 = anında kilitlenme.",
    tip_aimbot_start_bullet: "Aimbot yalnızca bu kadar mermi ateşlendikten sonra devreye girer.",
    tip_aimbot_distance_fov: "Uzaktaki hedefler için FOV aralığını otomatik genişletir.",
    tip_aimbot_visibility: "Yalnızca gerçekten görünen (duvarın arkasında olmayan) düşmanlara nişan al.",
    tip_aimbot_flash: "Yerel oyuncu flaş yemiş iken aimbot durur.",
    tip_aimbot_target_friendlies: "Takım arkadaşlarına da nişan al (FFA modları için).",

    section_triggerbot: "Triggerbot",
    triggerbot_delay: "Gecikme (ms)",
    triggerbot_shot_duration: "Atış Süresi (ms)",
    triggerbot_flash_check: "Flaş Kontrolü",
    triggerbot_scope_check: "Dürbün Kontrolü",
    triggerbot_velocity_check: "Hız Kontrolü",
    triggerbot_velocity_threshold: "Hız Eşiği",
    triggerbot_head_only: "Sadece Kafa",
    triggerbot_wallbang: "Wallbang",

    tip_triggerbot_enable: "Crosshair düşman üzerindeyken otomatik ateş eder.",
    tip_triggerbot_delay: "Ateş etmeden önce rastgele gecikme aralığı (ms), daha insani görünmesi için.",
    tip_triggerbot_shot_duration: "Sanal tıklamanın ne kadar süre basılı tutulacağı (ms).",
    tip_triggerbot_flash: "Flaş yenildiğinde ateş etme.",
    tip_triggerbot_scope: "Keskin nişancı silahlarında yalnızca dürbünde iken ateş et.",
    tip_triggerbot_velocity: "Bu hız eşiğinin üzerinde hareket ederken ateş etme.",
    tip_triggerbot_head_only: "Yalnızca crosshair düşmanın kafasının üzerindeyken ateş et.",
    tip_triggerbot_wallbang: "Duvar arkasındaki düşmana, mermi geçen silahlarda ateş et. Her silah için ayrı aç/kapa yapabilirsin.",

    section_rcs: "Geri Tepme Kontrolü (RCS)",
    rcs_strength: "Güç",
    rcs_mode: "Mod",
    rcs_smoothing: "Yumuşatma",
    tip_rcs_enable: "Silah geri tepişini mouse hareketiyle telafi eder.",
    tip_rcs_strength: "Eksen başına telafi gucu (0 = kapalı, 1 = tam telafi).",
    tip_rcs_mode: "Standalone: atarken her zaman aktif. Aiming: sadece aimbot bir hedefe kilitliyken aktif.",
    tip_rcs_smoothing: "Düzeltiyi birden fazla kareye yayar (0 = anlık, 0.9 = yavaş). RCS'yi daha doğal gösterir.",

    section_players: "Oyuncular",
    section_sound_esp: "Ses ESP",
    section_colors: "Renkler",

    player_esp_hotkey: "ESP Kısayolu",
    player_show_friendlies: "Takım Arkadaşlarını Göster",
    player_bomb_damage: "Bomba Hasarı",
    player_box: "Kutu",
    player_box_mode: "Kutu Modu",
    player_skeleton: "İskelet",
    player_head_circle: "Kafa Dairesi",
    player_health_bar: "Can Çubuğu",
    player_armor_bar: "Zırh Çubuğu",
    player_name: "Oyuncu İsmi",
    player_weapon_icon: "Silah İkonu",
    player_tags: "Etiketler",
    player_visible_only: "Sadece Görünenler",

    sound_footstep_radius: "Ayak Sesi Yarıçapı",
    sound_gunshot_radius: "Silah Sesi Yarıçapı",
    sound_weapon_radius: "Silah Yarıçapı",
    sound_fade_start: "Solma Başlangıcı (s)",
    sound_fade_duration: "Solma Süresi (s)",
    sound_show_visible: "Görünen Oyuncular İçin Göster",

    color_box_visible: "Kutu (görünür)",
    color_box_invisible: "Kutu (görünmez)",
    color_skeleton: "İskelet",
    color_player_name: "Oyuncu Adı",
    color_weapon_icon: "Silah İkonu",
    color_tags: "Etiketler (Bomba / Kask)",

    tip_player_enable: "Düşmanların üzerinde kutu, iskelet ve etiket göster.",
    tip_player_visible_only: "Yalnızca sana karşı görüş hattı açık olan oyuncuları çiz.",
    tip_player_show_friendlies: "Takım arkadaşları için de ESP çiz.",
    tip_player_health_bar: "ESP kutusunun sol tarafında can çubuğu göster.",
    tip_player_armor_bar: "ESP kutusunun sağ tarafında zırh çubuğu göster.",
    tip_player_tags: "Kutunun üzerinde bomba taşıyıcı / etkisizleştirici ikonu göster.",
    tip_sound_esp: "Son duyulan ayak sesi ve silah seslerini daire şeklinde göster.",
    tip_bomb_damage: "C4 patlamasından sonra her oyuncunun tahmini kalan canını göster.",

    section_hud: "HUD",
    section_text: "Metin",
    section_crosshair: "Keskin Nişancı Nişangahı",
    section_grenade_trails: "Grenad İzleri",
    section_radar: "Radar",

    hud_bomb_timer: "Bomba Sayacı",
    hud_fov_circle: "FOV Dairesi",
    hud_dropped_weapons: "Yere Düşmüş Silahlar",
    hud_keybind_list: "Tuş Listesi",
    hud_spectator_list: "İzleyici Listesi",
    hud_text_outline: "Metin Çerçevesi",
    hud_text_color: "Metin Rengi",
    hud_line_width: "Çizgi Kalınlığı",
    hud_font_size: "Yazı Boyutu",
    hud_icon_size: "İkon Boyutu",

    crosshair_enable: "Nişangahı Etkinleştir",
    crosshair_color: "Nişangah Rengi",
    crosshair_line_length: "Çizgi Uzunluğu",
    crosshair_line_width: "Çizgi Kalınlığı",
    crosshair_gap: "Boşluk",

    radar_enable: "Oyun İçi Radar Hack",
    radar_size: "Boyut (px)",
    radar_zoom: "Yakınlaştırma",
    radar_rotate: "Oyuncuyla Döndür",
    radar_show_names: "İsimleri Göster",
    radar_bg_alpha: "Arka Plan Saydamlığı",

    tip_hud_bomb_timer: "Bomba ekildiğinde geri sayım çubuğu ve 3D metin gösterir.",
    tip_hud_fov_circle: "Overlay üzerinde aimbot'un kilitleneceği yarıçapı daire olarak çizer.",
    tip_hud_spectator_list: "Sizi şu an izleyen oyuncuların listesini gösterir.",
    tip_crosshair_enable: "Dürbünlü silah kullanırken özel nişangah çizer.",
    tip_radar_enable: "Tüm düşmanların görülmüş bayrağını yazar; oyunun kendi mini haritasında görünürler.",
    tip_radar_rotate: "Oyuncu her zaman yukarıya bakacak şekilde radarı döndürür.",

    section_no_flash: "Flaş Engeli",
    section_fov_changer: "FOV Değiştirici",
    section_smokes: "Dumanlar",

    unsafe_no_flash: "Flaşı Engelle",
    unsafe_max_flash: "Maksimum Flaş Şeffaflığı",
    unsafe_fov_changer: "FOV Değiştirici",
    unsafe_desired_fov: "Hedef FOV",
    unsafe_no_smoke: "Dumanı Kaldır",
    unsafe_change_smoke_color: "Duman Rengini Değiştir",
    unsafe_smoke_color: "Duman Rengi",

    tip_no_flash: "Kör edici flaş efektini azaltır veya tamamen kaldırır.",
    tip_unsafe_max_flash: "0 = tamamen kör (flaş görünmez), 255 = normal flaş. Düşürdükçe flaş daha az kör eder.",
    tip_fov_changer: "Oyun içi görüş açısını geçersiz kılar.",
    tip_no_smoke: "Duman grenadı parçacık efektlerini kaldırır.",
    tip_change_smoke_color: "Dumanı özel düz bir renkle değiştirir.",

    section_config: "Yapılandırma",
    config_reset: "Legit Varsayılan",
    config_folder: "Config Klasörünü Aç",
    config_refresh: "Yenile",
    config_new_name: "Yeni config adı…",
    config_save_as: "Kaydet",
    config_delete: "Sil",
    config_load: "Yükle",
    tip_config_reset: "Tüm ayarları VAC güvenli legit ayarlara sıfırlar (aimbot/triggerbot/rcs/unsafe hepsi kapatılır, ESP açık kalır).",

    section_application: "Uygulama",
    app_language: "Dil",
    app_send_stacktraces: "Çökme raporu gönder",
    app_stacktraces_yes: "Evet – aracı geliştirmeye yardım et",
    app_stacktraces_no: "Hayır",
    tip_app_language: "Arayüz görüntüleme dilini seçin.",
    tip_send_stacktraces: "Hata ayıklamasına yardımcı olmak için çökme yığın izlerini otomatik gönderir.",
};

impl Language {
    pub fn strings(&self) -> &'static Strings {
        match self {
            Language::English => &LANG_EN,
            Language::Turkish => &LANG_TR,
        }
    }
}
